# Generated by Django 4.2.16 on 2024-12-18 23:27

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', django_summernote.fields.SummernoteTextField(max_length=3000, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='images')),
                ('image', models.FileField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
