# Generated by Django 4.2.16 on 2024-12-18 23:41

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companyProfileApplication', '0002_remove_services_image_alter_services_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=django_summernote.fields.SummernoteTextField(max_length=3000, null=True),
        ),
    ]
