# Generated by Django 4.2.16 on 2024-12-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyProfileApplication', '0003_alter_services_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
